### ISSUE TITLE
Website does not have a correct closing html tag

### ISSUE THREAD

**Issue by Tama63** [Jake0oo0/crafatar#60]
it's
`</html`
instead of
`</html>`

**Comment by jomo** [comment]
That's interesting since the HTML is generated by [jade](http://jade-lang.com/). Will look into it.

**Comment by jomo** [comment]
Okay, I think I found it. It must be caused by a faulty `Content-Length` header.

**Comment by jomo** [comment]
It's caused by the `×` (Multiplication sign, not x) character.

JavaScript's [`.length`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/length) "returns the number of code units in the string", not the byte count.
 
```js
"×".length
// => 1
```
However, the `×` character has 2 bytes:
```bash
$ echo -n "×" | xxd -p
c397
```

Apparently JavaScript has no way to return the actual byte count, unless you know the encoding:
```js
Buffer.byteLength("×", "UTF-8")
// => 2
```

**Comment by jomo** [comment]
fixed for index html, will need to check if we have this problem elsewhere though.

**Comment by jomo** [comment]
Other files (i.e. assets) are not affected because we use [`fs.readFile`](http://nodejs.org/api/fs.html#fs_fs_stat_path_callback) which gives us a buffer instead of a string.
